### ISSUE TITLE
Ensure relative linking works between different markdown and mdx documents

### ISSUE THREAD

**Issue by schpet** [onflow/next-docs-v1#118]
- [ ] find and document examples of documents with relative links in different repos
- [ ] configure markdown processing or html base tags to ensure linking works between anchor tags, img elements, etc

**Comment by kerrywei** [comment]
closing this as it's a duplicate of: https://github.com/onflow/next-docs-v1/issues/15 and https://github.com/onflow/next-docs-v1/issues/91
