### ISSUE TITLE
Create API utilities for StatusPage & Discourse

### ISSUE THREAD

**Issue by srinjoyc** [onflow/next-docs-v1#138]
We need API's to be able to pull information for the [Atlassian status page](https://developer.statuspage.io/) and the [discourse API](https://docs.discourse.org/) (our forum). 

For the status page, we need to display the network status in the navigation and the network status page. All fields that are shown there should be retrievable.

For discourse, we should be able to poll a topic to get the following - latest posts with titles, subtitles (if available), # of comments, date of last update.

You can see existing implementations of these API's on the current docs:
- https://github.dev/onflow/flow/blob/53ae4d47ebce621b56b7fbb0d79ff3ed0f1eced1/docs/plugins/gatsby-theme-flow/src/components/flow-status/hooks.js
- https://github.dev/onflow/flow/blob/7d1732ffd7e2e6f8f0347325ed9fec6ae869e6aa/docs/plugins/gatsby-theme-flow/src/components/flow-status/components/statusCard.js (for status text)

**Comment by srinjoyc** [comment]
Serve Event Data:
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/8709330/173103459-3c7f3ebe-5c6e-4dff-97da-8b657fc08c52.png">

**Comment by srinjoyc** [comment]
Featured Initatives:
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/8709330/173104028-8c4d82a3-5e5b-435d-9f9e-410fbc6e3ccd.png">

**Comment by srinjoyc** [comment]
Articles:
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/8709330/173104317-33ce1db7-46fd-46e5-b0ca-33dad68f823d.png">

Eventually could need to be pulled in from blog.onflow.org

**Comment by srinjoyc** [comment]
Tutorials:

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/8709330/173104691-480d38c4-d24a-420d-8fe0-93694fd54045.png">

**Comment by srinjoyc** [comment]
Videos:
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/8709330/173104851-fa6711a3-f01c-405f-98c0-f59d077f4e16.png">

**Comment by srinjoyc** [comment]
All content:
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/8709330/173104964-650961ba-37be-41db-a362-9e7fe2670207.png">

**Comment by srinjoyc** [comment]
All data sources outside of github and discourse will come from a json list initially.

**Comment by 10thfloor** [comment]
@codingone21 I believe we are finished with this, am I correct?

**Comment by codingone21** [comment]
> @codingone21 I believe we are finished with this, am I correct?
Just reviewed the changes, and not all of these are connected to the Be. 
Completed are FLIPS, Forum cells (From the Forum Section), Network. Not sure if the rest are pulled from .json or should be connected to the API
