### ISSUE TITLE
[due June 20] Rewrite relative links in markdown files

### ISSUE THREAD

**Issue by 10thfloor** [onflow/next-docs-v1#15]
How URLs to content should work (WIP):
- Loading a URL in the browser triggers first a cache lookup for content using the URL, eg. `/cadence/language/accounts` as the key, and if not found will call the github API using the first URL segment as the name of the repo (`cadence` so `onflow/cadence`) and the remaining segments as subfolders/files in thee repo's `docs` directory. 
- The final URL segment could either be a file with that name eg `accounts.mdx` or a folder named `accounts` containing and `index.mdx` file. The markdown file from either is 'downloaded' into Redis and rendered by the site at runtime on the server (SSR).

An example of a known issue to be solved: 

- A document lives in a repo a `/docs/language/transactions.mdx`
- A link in that page links to a file in the same subdirectory: `/docs/language/accounts.mdx`
- The link is written in the markdown file as: `[Accounts](accounts.mdx)` This is the correct format for sibling links to documents in the same folder in a github repo. However, this generates an `href` like `href=/accounts.mdx` when processed by the docs site markdown parser, since the parser is not aware of the context of the document (unlike with github).

The issue:

- There is no page in our docs site at the root level  `/accounts` so we must add the repo context, in the case of our example, we'd need to translate this into a _sibling_ link ie `/cadence/language/accounts`

- [ ] Investigation
    - A similar problem was addressed in the previous docs site so some code could be reused. 

There are other edge cases that link rewriting will need to handle:

- Links to documents in other repos
- Links to parent documents in the same repo
- Other?

Definition of done: 
- [ ] Links in all markdown files that are correctly formatted and work for navigating to other docs in their containing repos, or subheadings in their current doc work the same on the docs site. Navigation is consistent between repo and docs site.

**Comment by kerrywei** [comment]
update: 
pending tests before marking this is done
