### ISSUE TITLE
[Theme] Configure Tailwinds with style library

### ISSUE THREAD

**Issue by srinjoyc** [onflow/next-docs-v1#16]
# Context

Set up the theme file to reflect the [style library](https://www.figma.com/file/IhWAiD2gc7hgz1TLclY9ok/Style-Library-(External)?node-id=0%3A1).

# Acceptance Criteria

- [x] Screens set to breakpoints in "Artboards/Grids" screen
- [x] Spacing and sizes set as per the "Spacing" screen
- [x] Border radius and button colors definitions (primary, secondary, etc.) set as per the "Buttons" screen and "Tags" screen (`The theme contains all color and border-radius definitions, and buttons will be styled separately`)
- [x] Color palette and error/success classes as per the "Colors" screen including hover states
- [x] Gradients defined from the "Gradient Headers"
- [x] All type styles - fonts, size, and weight are defined as per the "Type Styles" screen
- [x] Include all icons in the "Icons" screen and the top row of icons (bookmark, dark/light mode, eyes) in the "Toggles" screen
- [ ] Add Acumin Pro semibold weight

**Comment by alse** [comment]
Update: This is ready for review in https://github.com/onflow/next-docs-v1/pull/32 . Adding the Add Acumin Pro semibold font weight is pending assets
