### ISSUE TITLE
Add all relevant repos to docs site via github action & search indexing

### ISSUE THREAD

**Issue by srinjoyc** [onflow/next-docs-v1#201]
We need add the following repos/content:
- [ ] onflow/flow repo located in this folder: https://github.com/onflow/flow/tree/master/docs/content (see note)
- [ ] onflow/fcl-js
- [ ] onflow/kitty-items
- [ ] onflow/flow-nft
- [ ] onflow/flow-go-sdk
- [ ] onflow/flow-ft
- [ ] onflow/nft-storefront
- [ ] onflow/flow-emulator
- [ ] onflow/flow-js-testing
- [ ] onflow/vs-code-extension
- [ ] All SDKs are located here: https://docs.onflow.org/sdks/
Note: Each folder in the `onflow/flow` repo (inside the `content` folder) should correspond to the top-level URL/route.
These repos should also be indexed in their `docs` folder.

Less critical but we should also add (unsure if these repos have docs setup correctly)
- onflow/fcl-dev-wallet
- onflow/flow-cadut
- onflow/sdks

**Comment by codingone21** [comment]
Steps:
1. Ensure we can render/fetch markdownfiles
2. How should we organize/design routing for these?

**Comment by codingone21** [comment]
Docs living inside /flow:
- [ ] onflow/flow/docs/content:

    + kitty-items
    + vs-code-extension

Docs in its own repositories:
- [ ] onflow/fcl-js
- [ ] onflow/flow-go-sdk
- [ ] onflow/flow-js-testing

Repositories missing /docs and not living in /flow:
- [ ] onflow/flow-nft (missing /docs)
- [ ] onflow/flow-ft (missing /docs)
- [ ] onflow/nft-storefront (missing /docs)
- [ ] onflow/flow-emulator (missing /docs)

SDKs:
- [ ] All SDKs are located here: https://docs.onflow.org/sdks/

**Comment by codingone21** [comment]
- Added /docs content and github actions to the 4 repos listed above (as missing /docs)
- Added /flow internal docs content with recreating routes in a generic way
    + Video for kitty-items not rendering anymore, will investigate

**Comment by neilZon** [comment]
I'll be taking over this task for the time being!
cc: @codingone21

**Comment by neilZon** [comment]
Update: 2 last PRs need to be merged to get `onflow/sdks` and `onflow/fcl-dev-wallet` to render on the docsite, however they have some concerns under them
