### ISSUE TITLE
[Components] Search

### ISSUE THREAD

**Issue by srinjoyc** [onflow/next-docs-v1#21]
# Context
Create the search UI as per the design [here](https://www.figma.com/file/aoIxdVZVGltGy4lWetuWKU/Component-Library-(External)?node-id=0%3A1) in the "Search" screen.

# Notes
- Investigate Algolia UI and functionality to determine any changes/details to the UI.

# Acceptance Criteria
- [ ] Search bar focuses and expands when clicked into the empty state shown
- [ ] Results show after a minimum of 3 letters
- [ ] External links or internal pages are identified by the icon
- [ ] Able to surface tags, date published, and breadcrumb trail - all as optional

**Comment by codingone21** [comment]
Update:
- Search design component is merged to Alex's branch
- Algolia team reached out, and we need to communicate with them to set up a crawler
