### ISSUE TITLE
UI Fixes for Short Term

### ISSUE THREAD

**Issue by srinjoyc** [onflow/next-docs-v1#222]
Few things to do in order to accommodate a 'alpha-preview':

Homepage Nav (@alse )
- [x] Icons need to be passed in for subsections alongside title and href - let's try a default of no icon - not a big fan of all the empty page icons now that I'm seeing it.
- [x] More spacing between the subsection items in the list (ideally even vertical distribution with equal padding at top and bottom), optimize for 6 elements or maybe increase font-size. Currently too much empty vertical space for the number of links.
- [x] Change section icons to map to design (cube icon, tool icon, etc.) - the grey colored ones.
- [x] Add hover state over the links (same light purple color)
- [x] Image inside of card (left side carousel) is not contained - larger images overflow onto the text. Should have max dimensions equal to the placeholder.
- [x] Hide search for now
- [x] Nav should close if I click away on the rest of the screen
 

Homepage: Quickstart Heading (3 column card) (cc: @aureentuluvacal )
 - [x] There is the padding on the header while there isn't on the body subtitle text. Both should be aligned to the same left edge.
 • I think the icon is supposed to be there but not showing?
 
![image](https://user-images.githubusercontent.com/8709330/174653386-4ea6f5cb-8270-42c2-8b5f-41395d7b62d3.png)

 
 Social Footer Component  (cc: @aureentuluvacal )
- [x] Grey border is appearing for one some boxes but not all - please review design
- [x]  Gradient looks like it gets cut off by container vs the gradient on the header which does not - the header version is preferred.
 
![image](https://user-images.githubusercontent.com/8709330/174653403-eeb13900-f2a4-4d09-9f4d-55c995d4d715.png)

 
 Route change   (cc: @aureentuluvacal )
 - [x] Change route from /builders -> /getting-started
 - [x] CMD + F for any references to /builders and replace

Events (@aureentuluvacal )
- [X] Finish events updates

**Comment by srinjoyc** [comment]
Critical Path
 • Merge in PRs from Friday (Alex)
 • Fix UI issues from today (Mack)
 • Merge in docs PRs on repo into 'dapp-development' (neil)
 • Event Data (abhinav)
 • Article Data (abhinav)
 • Missing Images & Icons (neil)
 • Add description to all tools -> ToolCardProps should be the same as SDKCardProps (neil)
 • Tools Data (Hannah)
 • Add GA: https://github.com/onflow/next-docs-v1/issues/193(hannah)
 • Tools Page (Srinjoy)
 • Learn Page (Srinjoy)
 • Community Page (Srinjoy)
 • Docs page update to highlight new portal (Srinjoy)

**Comment by srinjoyc** [comment]
Prioritze event card fixes (cc: @alse )

**Comment by neilZon** [comment]
> • Add description to all tools -> ToolCardProps should be the same as SDKCardProps (neil)
@srinjoyc how should we display the SDKCards if given description and commit date + last release date? Which one of the two should we show?
