### ISSUE TITLE
[Learn Page] All Content Section Updates

### ISSUE THREAD

**Issue by srinjoyc** [onflow/next-docs-v1#228]
Currently, if you click the next page button, there is a page jump that pushes your scroll down. We are also only showing 4 pieces of content, I think we should show 8 at a time (only for the "All Content" carousel - not all).

![image](https://user-images.githubusercontent.com/8709330/174658781-a491c6f4-4bb7-4c3f-a82a-3248166fde6b.png)

**Comment by neilZon** [comment]
Just to clarify, we want to remove that scroll when we click the next button?
