### ISSUE TITLE
Upload all image from this dropbox to a CDN

### ISSUE THREAD

**Issue by srinjoyc** [onflow/next-docs-v1#250]
Have the following assets available: https://www.dropbox.com/sh/5z8cfonblsycxj1/AACbXQwa8aFbgkM23GX5gnnSa?dl=0 
(ideally in 1x and 2x sizes for the respective artwork as well if possible).

**Comment by neilZon** [comment]
Update: I have the images in 1x and 2x sizes but waiting for some sort of asset CDN to serve these as I don't want to put these in the app and enlarge the bundle (unless we need the images asap, in which case I will add them)

**Comment by neilZon** [comment]
Update: Opened up ticket to IT and now getting redirected to SRE

**Comment by neilZon** [comment]
Update: Images are uploaded to a GCP bucket, not really sure where to list the URLs of the images for the team to use

**Comment by neilZon** [comment]
Image urls:
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Illustrations-clouds-2@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-illustration-GreenLeaf@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow_Green-Asset_6.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-illustration_Drop-v1.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-2@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Green-Asset-4@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Illustration-shoe@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow_Green-Asset_5.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-illustration_Drop-v2.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow_Illustration-green.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow_Green-Asset_4.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/.DS_Store
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-15@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow_Green-Asset_1.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow_Green-Asset_3.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Illustrations-cubes-1@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-illustration-Drop-v2@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Illustration-green@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Green-Asset-6@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow_Green-Asset_2.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-4.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Illustration_L-Sphere.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-10.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-11@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow_Illustrations-cube-2.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-11.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-5.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-4@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Illustration_shoe.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-7.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Illustrations-cube-2@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Illustration_Sphere-x-Box.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-13.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-8@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Green-Asset-2@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow_Illustrations-cube-G.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Illustrations-clouds-4@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-12.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow_Illustrations-clouds-4.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-6.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-2.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Illustration_bike.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-6@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Ilustration_Hands.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Illustrations-blocks@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-illustration-CreditLeaf@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow_Illustrations-clouds-1.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-illustration-Energy@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-3.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Illustration-bike@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-1.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-13@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow_illustration_Energy.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow_illustration_GreenLeaf.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow_Illustrations-clouds-3.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-15.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-illustration_head_noextra.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Ilustration-Hands@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow_Illustration-energy.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-14.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow_Illustrations-clouds-2.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Illustrations-cube-G@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-illustration_head.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-3@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Green-Asset-5@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow_Illustrations-blocks.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Illustrations-clouds-3@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-illustration-Drop-v1@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-illustration-head@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-1@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Illustrations-clouds-1@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Illustration-Sphere-x-Box@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-14@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-8.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-illustration-head-noextra@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-9.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Illustration-abstract-cube-2@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-5@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Green-Asset-3@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-9@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow_illustrations-Water.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Illustration-L-Sphere@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow_Illustrations-cubes-1.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-10@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow_illustration_CreditLeaf.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-illustrations-Water@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-12@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow-Green-Asset-1@2x.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Flow_Illustration-abstract-cube-2.png
https://storage.googleapis.com/flow-resources/documentation-assets/new-docsite-assets/Asset-7@2x.png
