### ISSUE TITLE
Broken Internal Pages

### ISSUE THREAD

**Issue by neilZon** [onflow/next-docs-v1#292]
# Description
Some of the internal pages have errors when you try to access them and this is a list of what pages have what errors

~~**Note 1** This only tests the `cadence/...` pages, this list is probably gonna get bigger~~
**Note 2** atm, we have a redirect to a "coming soon" if you try to access a page that isn't one of the landing pages so you won't be able to see the page errors if you click on the links below
<br/>

## Repos Tested So Far

-   cadence
-   fcl-js
-   flow-go-sdk
-   flow-js-testing
-   Flow/content
      - bounties
      - community-updates
      - concepts
      - core-contracts
      - faq
      - emulator
      - faq
      - flow-port
      - flow-token
      - fusd
      - intro
      - kitty-items
      - nft-marketplace
      - node-operation
      - staking
      - vscode-extension
 - flow-cadut
 - flow-nft
 - flow-ft
 - flow-emulator
 - nft-storefront
<br/>

### Callout Issues
Console: 
```
Error: Expected component `Callout` to be defined: you likely forgot to import, pass, or provide it.
```

- [x] https://developers.onflow.org/cadence/anti-patterns
- [x] https://developers.onflow.org/cadence/language/accounts
- [x] https://developers.onflow.org/cadence/language/built-in-functions
- [x] https://developers.onflow.org/cadence/language/composite-types
- [x] https://developers.onflow.org/cadence/language/resources
- [x] https://developers.onflow.org/cadence/language/interfaces
- [x] https://developers.onflow.org/cadence/language/values-and-types

### MDX Render Error #347 

- [x] /fcl-js/reference/api
- [x] http://localhost:3000/flow/content/concepts/transaction-lifecycle
- [x] http://localhost:3000/flow/content/concepts/variable-transaction-fees
- [ ] http://localhost:3000/flow/content/dapp-development/dapp-infrastructure/deployment
- [ ] http://localhost:3000/flow/content/dapp-development/dapp-infrastructure/flow-dapp-anatomy
- [ ] http://localhost:3000/flow/content/dapp-development/dapp-infrastructure/in-dapp-payments
- [x] http://localhost:3000/flow/content/dapp-development/smart-contracts
- [x] http://localhost:3000/flow/content/flow-token
- [x] http://localhost:3000/flow/content/flow-token/wallets
- [x] http://localhost:3000/flow/content/intro/flow-token
- [x] http://localhost:3000/flow/content/node-operation/leased-account-setup
- [ ] http://localhost:3000/flow/content/node-operation/node-roles
- [x] http://localhost:3000/flow/content/node-operation/node-setup
- [x] http://localhost:3000/flow/content/node-operation/guides/genesis-bootstrap
- [ ] http://localhost:3000/flow/content/staking/staking-scripts-events

---

- [x] https://developers.onflow.org/cadence/language/functions
- [x] https://developers.onflow.org/cadence/language/glossary
- [x] https://developers.onflow.org/cadence/tutorial/01-first-steps.mdx
- [x] https://developers.onflow.org/cadence/tutorial/05-non-fungible-tokens-1.mdx
- [x] https://developers.onflow.org/cadence/tutorial/06-non-fungible-tokens-2.mdx
- [x] https://developers.onflow.org/cadence/tutorial/10-resources-compose.mdx

<br/>

## Page Renders But With Warnings #348 
- [x] /fcl-js/index
Log file: [localhost-1655934965843.log](https://github.com/onflow/next-docs-v1/files/8961613/localhost-1655934965843.log)
- [x] /fcl-js/tutorials/flow-app-quickstart
Log file: [localhost-1655935034442.log](https://github.com/onflow/next-docs-v1/files/8961620/localhost-1655935034442.log)
- [x] /fcl-js/reference/sdk-guidelines
Log file: [localhost-1655935706465.log](https://github.com/onflow/next-docs-v1/files/8962083/localhost-1655935706465.log)

## Renders without table #352

- [x] http://localhost:3000/flow/content/bounties
- [x] Works but tables not rendering...

## Awkward title #354

- [x] http://localhost:3000/flow/content/concepts/token-staking

![Screen Shot 2022-06-27 at 2 17 00 PM](https://user-images.githubusercontent.com/46465568/176034735-4e5e3f0f-a44a-429c-a6a5-cf31e27a9ecf.png)

## Image paths need to be rewritten #350
- [x] http://localhost:3000/flow/content/dapp-development/NFT-drop-styles
- [x] http://localhost:3000/flow/content/flow-port/staking-guide
- [x] http://localhost:3000/flow/content/dapp-development/mainnet-account
- [x] setuphttp://localhost:3000/flow/content/kitty-items
- [x] http://localhost:3000/flow/content/kitty-items/install (missing video player)
- [x] http://localhost:3000/flow/content/kitty-items/modify
- [x] http://localhost:3000/flow/content/kitty-items/start
- [x] http://localhost:3000/flow/content/staking/epoch-scripts-events
- [x] http://localhost:3000/flow/content/staking/schedule
- [x] https://developers.onflow.org/cadence/language/type-hierarchy
- [x] /fcl-js/reference/discovery

**Comment by 10thfloor** [comment]
This is great!

**Comment by 10thfloor** [comment]
I fixed the `Callout` issue yesterday, so we shouldn't see those anymore.

**Comment by srinjoyc** [comment]
Thanks @neilZon - very helpful! Are we trying this out with other repos as well - did you see the list here: https://github.com/onflow/next-docs-v1/issues/201 - we'll need all these in before next week so would like to know where we stand if possible.

**Comment by neilZon** [comment]
@srinjoyc No problem! Yep, I just went over the following repos and their issues should now be recorded, just waiting for the sdk's and repos that have missing docs
cadence
fcl-js
flow-go-sdk
flow-js-testing
