### ISSUE TITLE
[Components] Create storybook components for "Internal Pages"

### ISSUE THREAD

**Issue by srinjoyc** [onflow/next-docs-v1#3]
# Context
The internal page components can be found here: https://www.figma.com/file/aoIxdVZVGltGy4lWetuWKU/Component-Library-(External)?node-id=0%3A1

# Acceptance Criteria

The following components can be created from the internal reference:
- [x] H1, H2, H3, H4, H5, H6
- [x] #29
- [x] Attribution elements
- [x] Paragraphs
- [x] Sidebar menu overlay
- [x] Sidebars
- [x] Interior Page Layout
- [x] Lists
- [x] Links 
- [x] Quotes
- [x] Images
- [x] Table
- [x] Callouts (skip upload callout)
- [x] Lower page navigation
- [x] Footnotes
- [x] Breadcrumbs
- [x] Version picker

Interior Landing Page components (located in "Landing Page components in the component library):
- [x] "Cadence Header"
- [X] "Cadence Card"
- [x] "Cadence Header Card"
*Note that I would change the naming of these as they will be used generically for any tool*

**Comment by alse** [comment]
Status update:
- Created storybook components for headings, attributions, paragraphs, left sidebar, table of contents sidebar
- Created the interior page layout, and connected everything except attributions and the left nav to the markdown renderer

Next steps: 
- Discuss codeblocks and nav switcher
- Add any other components from the interior page design

**Comment by alse** [comment]
@srinjoyc I added the remaining components under `Additional components` above, let me know if any are missing

**Comment by srinjoyc** [comment]
Thanks @alse - double checked [here](https://www.figma.com/file/aoIxdVZVGltGy4lWetuWKU/Component-Library-(External)?node-id=0%3A1) and that looks accurate!

**Comment by alse** [comment]
Status update:
- Added Tables, Callouts, Lower page nav, Breadcrumbs, Internal version select, Internal sidebar menu in #40 .
- Footnotes are partially finished, and waiting for mdx rendering

Next steps:
- Interior Landing Page components

**Comment by alse** [comment]
Status update:
- Finished the cadence header & cards
- @srinjoyc I added the title/cta/image section to the list as "Intro section" (From [Tool landing page)](https://www.figma.com/file/704SXr4HrUbIIkXYena62Q/Flow-Dev-Portal-(External)?node-id=1706%3A58937)

Next steps:
- Intro section and codeblock

**Comment by alse** [comment]
@srinjoyc I added the code block styling + modal in #75 . I'll check it off as done in this issue, and we can continue any code highlighting + mdx rendering work as part of #29
