### ISSUE TITLE
SDK and Tool Card Icons Sizing

### ISSUE THREAD

**Issue by srinjoyc** [onflow/next-docs-v1#300]
All icons used for SDKs and tools should be the same size.
![image](https://user-images.githubusercontent.com/8709330/175346957-4c31a827-3820-4dd8-aa7d-614bb24652b9.png)

It May be related to the tools card and SDK card being different - these should probably be the same.

**Comment by kerrywei** [comment]
note: Hannah to check with Cal to avoid dup work

**Comment by codingone21** [comment]
Synced with Cal, she will be working on this as a part of icon/imaging work!
