### ISSUE TITLE
Make 'Page Sections' linkable

### ISSUE THREAD

**Issue by srinjoyc** [onflow/next-docs-v1#305]
For any `<PageSection>` require a sub route that can access it `ie. #cadence` in the the `/learn#cadence` page should go directly to the Cadence carousel. This should also work for internal pages.

**Comment by neilZon** [comment]
It seems that all the internal pages have a button to go to the section when you hover over the header, should we add this button link to all the landing pages too?
![Screen Shot 2022-06-23 at 3 07 41 PM (2)](https://user-images.githubusercontent.com/46465568/175400096-96566b05-df96-483f-923a-d96b6a00ecc0.png)

**Comment by srinjoyc** [comment]
Yeah, I'd like to see what that would look like - if it doesn't work maybe we remove it, but lets try it out and post a screenshot

**Comment by neilZon** [comment]
Here's what it would look like, but the chain icon only appears when the header is hovered on
![Screen Shot 2022-06-23 at 4 43 17 PM (2)](https://user-images.githubusercontent.com/46465568/175427074-4dc4b4ff-8676-48ce-9b00-4babad28d05e.png)
