### ISSUE TITLE
MDX component support

### ISSUE THREAD

**Issue by schpet** [onflow/next-docs-v1#344]
it appears that MDX components are not currently supported 

1. note the `<Callout>` mdx component is used in cadence anti patterns with the text "This anti-pattern has been addressed with [FLIP #703]…" https://github.com/onflow/cadence/blame/5a06fec82b4ab90d3fd770abb6b75ab56f2b51cd/docs/anti-patterns.mdx#L185
1. visit https://flow-docs-staging.fly.dev/cadence/anti-patterns
1. note that the component isn't shown, and the "This anti-pattern has been addressed" text is not present

**Comment by alse** [comment]
Reopened by #372
