### ISSUE TITLE
404 Pages

### ISSUE THREAD

**Issue by neilZon** [onflow/next-docs-v1#349]
# Description
When the following pages are rendered on the docsite, the console prints a '404 could not find' error

related #292

- [ ]  https://developers.onflow.org/cadence/language/functions
- [ ]  https://developers.onflow.org/cadence/language/glossary
- [ ]  https://developers.onflow.org/cadence/tutorial
- [ ]  https://developers.onflow.org/cadence/tutorial/01-first-steps
- [ ]  https://developers.onflow.org/cadence/tutorial/03-fungible-tokens
- [ ]  https://developers.onflow.org/cadence/tutorial/04-non-fungible-tokens
- [ ]  https://developers.onflow.org/cadence/tutorial/05-marketplace-setup
- [ ]  https://developers.onflow.org/cadence/tutorial/06-marketplace-compose
- [ ]  https://developers.onflow.org/cadence/tutorial/07-resources-compose
- [ ]  https://developers.onflow.org/cadence/tutorial/08-voting

**Comment by schpet** [comment]
after a quick look, some of these are 500 errors related to mdx processing

http://localhost:3000/cadence/tutorial/01-first-steps

and some of these are broken links, i.e. an equivalent doc doesn't exist in [the cadence repo](https://github.com/onflow/cadence/tree/master/docs/tutorial)

http://localhost:3000/cadence/tutorial/07-resources-compose

so i think the 404 behavior is correct here, and the remaining stuff is likely better addressed by #347 – what do you think @neilZon ?

**Comment by neilZon** [comment]
Ah you're right, these URL's aren't referencing the names of any of the files in the cadence repo. However, I'm finding more 500 errors but I'll append those to the list in #347. I'm gonna close this issue, but thanks for the catch!
