### ISSUE TITLE
Page Renders with Stacktrace error

### ISSUE THREAD

**Issue by neilZon** [onflow/next-docs-v1#351]
# Description
Page renders with a stacktrace error 
![Screen Shot 2022-06-28 at 1 30 50 PM](https://user-images.githubusercontent.com/46465568/176269206-26eef8ed-759f-4c8e-ab8d-e376cebe8ba4.png)

related #292

Affected pages:
- [ ] /flow-go-sdk/index
Log file: [localhost-1655934440222.log](https://github.com/onflow/next-docs-v1/files/8961585/localhost-1655934440222.log)

**Comment by joekrill** [comment]
This doesn't appear to be happening anymore as far as I can tell - I'm unable to reproduce it.
