### ISSUE TITLE
FAQ with collapsables

### ISSUE THREAD

**Issue by srinjoyc** [onflow/next-docs-v1#37]

**Comment by neilZon** [comment]
**description**
Add collapsable FAQ components as outlined in https://www.figma.com/file/aoIxdVZVGltGy4lWetuWKU/Component-Library-(External)?node-id=0%3A1

**Acceptance Criteria**
- [ ] Expand and collapse FAQ on click
- [ ] Desktop and mobile styling
- [ ] Large and small variation for desktop screens

**Comment by neilZon** [comment]
update: awaiting review
