### ISSUE TITLE
Update Icons & Images

### ISSUE THREAD

**Issue by srinjoyc** [onflow/next-docs-v1#378]
Upload the following logos from this [file](https://www.figma.com/file/Bf3brjLBdiunIH8IIfcWcr/Permissionless-Deployment?node-id=199%3A869)
![image](https://user-images.githubusercontent.com/8709330/177383805-90f2caa6-fab9-49ea-855b-94091e6bf3bf.png)
- used for any playground icon.

![image](https://user-images.githubusercontent.com/8709330/177383825-4eff36cc-3a2b-4c61-a878-39de2bb1675e.png)
- used as image for any playground cards (in the nav)

![image](https://user-images.githubusercontent.com/8709330/177384925-cc653217-d04b-4cc5-986d-4c88dae8fc89.png)
- (multiple sizes needed) - needs to display similar to the 'running man' logo of Cadence for FCL's 'homepage'
- used as default icon for FCL

![image](https://user-images.githubusercontent.com/8709330/177384064-930a2b52-5b35-4804-8cb2-e51d5622e087.png)
- used as default for any tool/service that does not have a logo

![image](https://user-images.githubusercontent.com/8709330/177384080-7c704507-e343-4393-925e-38caa102395c.png)
- used as default for any article that does not have a logo

![image](https://user-images.githubusercontent.com/8709330/177384109-cc6f45d5-4a8e-400b-905f-bef5114ee0e0.png)
- (multiple sizes needed) - needs to display on the 'events' carousel where the large discord logo is right now.
![image](https://user-images.githubusercontent.com/8709330/177384135-684d08f5-2261-4acc-b4c1-3e82e552b1f3.png)
- used as icon for dev-wallet tool
![image](https://user-images.githubusercontent.com/8709330/177384171-8c2693a0-5a53-4a11-bb50-25d572c953ff.png)
- (multiple sizes needed) - needs to display similar to the 'running man' logo of Cadence for FCL's 'homepage'
- used as default icon for node operation or spork-related callouts/cards.
![image](https://user-images.githubusercontent.com/8709330/177384196-93e56e96-3fe9-461f-8e8e-39a97ef3dc6d.png)
- TBD usage, would just keep in multiple sizes for now in the repo for later use.

Landing page images to update:
Replace the landing page images with the images shown in the figma files for 'learn, community, tools':
![image](https://user-images.githubusercontent.com/8709330/177385676-1c705ea6-3a9e-4f8b-9684-ea3dadf3a1de.png)

**Comment by aureentuluvacal** [comment]
@aureentuluvacal Me, work on this tomorrow:
- Fix FCL size on tool cards
- Shrink office hours size and see if it renders
