### ISSUE TITLE
"Video Cards"

### ISSUE THREAD

**Issue by srinjoyc** [onflow/next-docs-v1#38]

**Comment by neilZon** [comment]
description
Add video card components for mobile and desktop https://www.figma.com/file/aoIxdVZVGltGy4lWetuWKU/Component-Library-(External)?node-id=0%3A1

Acceptance Criteria
- [ ] Video card player component large and small screen styling, note the on hover styling
- [ ] Video card that brings user to external link, note the on hover styling
- [ ] Accepts a youtube url for the initial MVP

**Comment by neilZon** [comment]
update: #52 awaiting approval
