### ISSUE TITLE
[Metrics] Add a mixpanel event for any cache updates

### ISSUE THREAD

**Issue by srinjoyc** [onflow/next-docs-v1#384]
We want to measure the number of times contributions that cause a change in the docs content to be measured. 
At minimum we should be able to count the total number of commits merged in that updated the dev portal (from any repo).
At best we could also have the following info:
- Ability to segment by contributor (ie. Srinjoy contributed 5 times)
- Ability to segment by repository (ie. Cadence updated 4 times)

**Comment by neilZon** [comment]
Update: After some investigation, concluded that this entails going to each of the repos we want to render on the website and updating their call-refresh GitHub action to also capture commits when calling the refresh endpoint

**Comment by neilZon** [comment]
Update: After some issues with the above implementation, found https://docs.github.com/en/graphql/reference/objects#pullrequest which I will explore

**Comment by 10thfloor** [comment]
@neilZon I don't think we need to add an event to the github action. 
The action sends the commit sha and the repo here: 
https://github.com/onflow/next-docs-v1/blob/main/app/routes/action/refresh.tsx#L2

What if we wrote another github api call that uses the sha and the repo to fetch the contributor? 

If we could do that we wouldn't need to modify the deployed actions. 

We'll be deprecating those actions soon, hopefully, in favor of using a webhook-based approach, at which point we could offload this to the webhook.

**Comment by neilZon** [comment]
What about the case where we have commits from multiple contributors in a merge event? I've been tinkering around with this approach that would only require a change in the https://github.com/onflow/flow/blob/master/.github/workflows/refresh-doc.yml workflow in the 

But given that we are going to deprecate the action, there'll probably be an easier way to capture all the event data in a merge event webhook

```
    - uses: actions/github-script@v4
      id: stringifyEvent
      with:
        script: |
          const contributorCommitCount = context.payload.commits.reduce((contributorCommitCount, commit) => {
            const author = commit.author.username
            if (commit.author.username in contributorCommitCount) contributorCommitCount[author] += 1
            else contributorCommitCount[author] = 1
            return contributorCommitCount
          }, {})
          const contributionCountArr = Object.entries(contributorCommitCount).map(([contributor, commitCount]) => ({
            contributor,
            commitCount
          }))
          return JSON.stringify(contributionCountArr)
        result-encoding: string

    - name: 📞 Call refresh endpoint
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://webhook.site/892cb3ec-b9cf-4518-899c-6118eeee31cf'
        method: 'POST'
        data: '{ "auth":"authToken", "repo":"${{ inputs.repository }}", "commitSha":"${{ inputs.commitSha }}", "contentPaths":["${{ inputs.contentPaths }}"], "contributions": ${{ steps.stringifyEvent.outputs.result }} }'
        ignoreStatusCodes: '404'
```
