### ISSUE TITLE
Tool switcher renders under main content

### ISSUE THREAD

**Issue by joekrill** [onflow/next-docs-v1#395]
You can see 2 issues here we can address in this issue: 

https://user-images.githubusercontent.com/901466/177648418-2501c476-6382-4943-aded-76740172b1ad.mov

- [ ] The menu opens with incorrect z-index
- [ ] The menu is scrollable side-to-side
- [ ] Icon for "active" tool not rendering

**Comment by 10thfloor** [comment]
You can see 2 issues here we can address in this issue: 
https://user-images.githubusercontent.com/901466/177648191-d80a7124-524a-4c16-987c-e331ba4dbce4.mov

- [ ] The menu opens with incorrect z-index
- [ ] The menu is scrollable side-to-side
