### ISSUE TITLE
Internal mdx pages with Youtube iframe embeds do not show videos

### ISSUE THREAD

**Issue by schpet** [onflow/next-docs-v1#446]
from #415 

visit https://flow-docs-staging.fly.dev/tools/fcl-js/tutorials/flow-app-quickstart

expected: youtube video should load
actual: no video is shown

reference mdx:

https://github.com/onflow/fcl-js/blob/25c2d79bfaf12674d1745e6894c0a543f54574ba/docs/tutorials/flow-app-quickstart.mdx?plain=1#L13

**Comment by joekrill** [comment]
Fixed by #447
