### ISSUE TITLE
Routing Refactor

### ISSUE THREAD

**Issue by 10thfloor** [onflow/next-docs-v1#458]
Establish a pattern for consuming repository content

**Constraints:** 
- The name of the repository should be used somewhere in the URL
   - repository names should be used as-is in some portion of a URL that is meant to read content from it. Doing this will prevent URL collisions
- Paths to contents within repositories can't be renamed 
    - We don't want to provide the ability to rename content within repositories. If authors desire different URLs the containing repo should be reorganized.

**Goals:**
- [ ] Possible to have a custom sidebar for every unique URL
- [ ] Possible to specify arbitrary route metadata for every URL
- [ ] Repo content can be fetched when repo name is non-root eg: /tools/fcl-js and this can be configured to an arbitrary depth
- [ ] Route data and sidebar menus are co-located with route files
- [ ] Should be possible to display a mix of repos content and 'native' content. eg /tools/fcl-js -> repo content & tools/overview -> custom page in the Remix app

**Comment by alxflw** [comment]
as we discussed on Friday- this is a nice to have for the launch. OK to push out in favor of high prio items

**Comment by schpet** [comment]
related label:

https://github.com/onflow/next-docs-v1/labels/Route%20refactor

**Comment by joekrill** [comment]
Closed by #504
