### ISSUE TITLE
Get all links and check content

### ISSUE THREAD

**Issue by alxflw** [onflow/next-docs-v1#464]
As per discussion, we should check that all pages are 1) merged and 2) rendering as expected.

@10thfloor wanted to check if redis could be used to collect a list of all links

**Comment by 10thfloor** [comment]
We have the list!
https://docs.google.com/spreadsheets/d/1VdWq4_nhLcybMoU49jIKinlmMjtrbKT-DCOuNrzM0_Y/edit#gid=1972038406

**Comment by 10thfloor** [comment]
Links have been checked.
