### ISSUE TITLE
UI rendering bug

### ISSUE THREAD

**Issue by alxflw** [onflow/next-docs-v1#467]
Oftentimes when I click a link, I get the following view in which the page is seemingly loaded twice and split in half horizontally:

<img width="1491" alt="Screen Shot 2022-07-19 at 8 12 35 AM" src="https://user-images.githubusercontent.com/97620081/179787549-aca2490d-db3f-466e-919c-4fad8a128175.png">

I don't see a pattern but this has been reported by @a5chanda as well

**Comment by aureentuluvacal** [comment]
@alxflw @a5chanda @codingone21 can you tell me if you're still seeing this issue after restarting the docker containers and reinstalling all the dependencies?

**Comment by alxflw** [comment]
just experienced it again. it's a very nasty bug. refreshing a dozen times usually helps. appearance/fix seems random after a couple refreshes (with and without cache, tried it all)

**Comment by alxflw** [comment]
no, I don't run the project locally. this is on developers.onflow.org

**Comment by joekrill** [comment]
I don't think developers.onflow.org has the latest code (I notice a bug that I fixed last week is still happening there). I wonder if maybe this is no longer an issue? Has this happened on any other environments?  @alxflw is there a particular link (or type of link) you are clicking that ultimately triggers this?

**Comment by alxflw** [comment]
I don't get it on https://flow-docs-staging.fly.dev. This is not limited to a particular link or type

**Comment by alxflw** [comment]
@aureentuluvacal can you please deploy the latest to prod and ensure this bug is gone?

**Comment by alxflw** [comment]
i just confirmed, it is resolved in prod now
