### ISSUE TITLE
Understand how to set up redirects from docs to portal

### ISSUE THREAD

**Issue by alxflw** [onflow/next-docs-v1#475]
As per our discussion today, let's identify how we can set up redirects to cover the 200+ 404s we would see once we switch to the portal.

URL crawler data for new site:
https://docs.google.com/spreadsheets/d/1VdWq4_nhLcybMoU49jIKinlmMjtrbKT-DCOuNrzM0_Y/edit#gid=1972038406

Ongoing PR here: https://github.com/onflow/next-docs-v1/pull/489

**Comment by alxflw** [comment]
note: make sure to set up 301s (permanent)

**Comment by 10thfloor** [comment]
@alxflw Can you link the google analytics data that you pulled here, and any other URL data-sets you have access to?
I can't recall how we will understand which links need a redirect.

**Comment by 10thfloor** [comment]
eg: https://docs.google.com/spreadsheets/d/1VdWq4_nhLcybMoU49jIKinlmMjtrbKT-DCOuNrzM0_Y/edit#gid=1972038406

**Comment by 10thfloor** [comment]
Our deployment provider Fly.io does not support _config-based redirects_ for their deployments, unlike Vercel. 
Our 301s will have to be defined in the Remix application. I thnk we'll need to use this Remix convention: 
https://remix.run/docs/en/v1/api/conventions#routes

**Comment by alxflw** [comment]
got it. in what format would the list need to be?

**Comment by 10thfloor** [comment]
JSON would be preferred. Otherwise, any language-agnostic format should work (eg csv, yaml ...etc)
