### ISSUE TITLE
Simplify URL structure and content spec data

### ISSUE THREAD

**Issue by schpet** [onflow/next-docs-v1#487]
this is about the "content spec" data in [app/constants/repos/index.ts](https://github.com/onflow/next-docs-v1/blob/be19a3d5862ef3dfaa3885bf8a3288e2f93dbb0f/app/constants/repos/index.ts)

right now `app/routes/$repo/$.tsx` handles all requests for external content and conditionally loads content based on the content spec. there is a lot of branching that make this complex to work with ([example](https://github.com/onflow/next-docs-v1/blob/be19a3d5862ef3dfaa3885bf8a3288e2f93dbb0f/app/routes/%24repo/%24.tsx#L52-L101)) so the idea is to simplify the data structure.

recommendations

- single static json file with a list of all repositories and their relevant data including content (e.g. repo owner, repo name, sidebar data, etc)
  - including nested sidebar data, e.g. cadence [tutorial](https://developers.onflow.org/cadence/tutorial/05-non-fungible-tokens-1) vs [language](https://developers.onflow.org/cadence/language) vs [default](https://developers.onflow.org/cadence/anti-patterns) sidebars
- keep [onflow/flow](https://github.com/onflow/flow) stuff __separate__ from the repo level data, to avoid conflating content like [kitty-items](https://github.com/onflow/flow/tree/master/docs/content/kitty-items) with external repos – onflow/flow is special
- introduce 5 top level routes: tools, learn, flow, nodes, community
  - e.g. `app/routes/tools/$.tsx`, `app/routes/learn/$.tsx` etc
  - given a url like `/learn/foo/bar` these routes will look at the first url segment `foo`: if there is a known repo named `foo` then it will load the `bar` document from the `foo` repo, otherwise it will try and load a document from the [onflow/flow repos docs/content directory](https://github.com/onflow/flow/tree/master/docs/content)
    - e.g. `/learn/kitty-items` will load https://github.com/onflow/flow/blob/master/docs/content/kitty-items/index.md
    - e.g. `/learn/flow-ft/overview` will load https://github.com/onflow/flow-ft/blob/master/docs/overview.md

open questions

- [ ] can we get a mapping of repos to top level namespaces? i.e. does cadence live at /cadence, or does it live at /learn/cadence or /tools/cadence etc

**Comment by joekrill** [comment]
Closed by #504
