### ISSUE TITLE
Allow loading the sidebar when mdx errors occur

### ISSUE THREAD

**Issue by schpet** [onflow/next-docs-v1#488]
when we visit an internal page, e.g. a url like 
https://developers.onflow.org/cadence/tutorial/05-non-fungible-tokens-1

and the mdx fails, the sidebar should still load

this might require using multiple routes, e.g.

```
app/routes/$repo.tsx   // loads sidebar data, renders outlet
app/routes/$repo/$.tsx // loads mdx document

// after #487  is done, more routes too
app/routes/learn/$path.tsx   // loads sidebar data, renders outlet
app/routes/learn/$path/$.tsx // loads mdx document

```

**Comment by 10thfloor** [comment]
Added this in: https://github.com/onflow/next-docs-v1/pull/531
