### ISSUE TITLE
Create Refresh Endpoint

### ISSUE THREAD

**Issue by srinjoyc** [onflow/next-docs-v1#5]
This endpoint will be hit every time any of the registered repos that have our GitHub action enabled. 

This should update the cache with new content. 

Endpoint will receive list of files that were changed, renamed, or deleted

When content is changed: 
- download new content and cache (using existing 'getMDXPage` method)

When content is deleted: 
- Should check the cache and remove any cached content and the cache key for that content

---

When content has been renamed: 
**This needs to be designed still**
- This is equivalent to a redirect since the same content is now accessible via a new URL
- We need to map the old content to the new path and create a new cache entry for that content
Questions: 
- How to keep track of changing URLs over time? 
    - Inn the current site we use a big JSON file. https://github.com/onflow/flow/blob/master/docs/vercel.json
- What to do with cached content?
- ... ?

Any solutions proposed should be added to the design doc: 
[Design Doc](https://www.notion.so/dapperlabs/New-Docs-Site-Technical-Requirements-87d502531e484735853e88e02902de25#659da2b42ca840a980e951d85d5e93fa)

**Comment by 10thfloor** [comment]
Refresh endpoint is created. I'm going to test this is working now that the deployment is working.
