### ISSUE TITLE
[Aug 9] Launch UI Issues

### ISSUE THREAD

**Issue by srinjoyc** [onflow/next-docs-v1#510]
Leave as comments below on any minor ones you find!

**Comment by srinjoyc** [comment]
Change the hashtag of preview:
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/8709330/183700861-845b20a2-51a4-4144-a051-e133d6f4f3f0.png">

**Comment by srinjoyc** [comment]
Need to update all events:
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/8709330/183705167-a26ed714-36d9-413b-ad05-1970fedae936.png">

**Comment by alxflw** [comment]
> Change the hashtag of preview:

what should be the new hashtag?

**Comment by srinjoyc** [comment]
#onflow - is what was on the design. open to other suggestions if any but I think that works for now

**Comment by srinjoyc** [comment]
This is in the wrong place: 
https://flow-docs-staging.fly.dev/tools/fcl-js/reference/sdk-guidelines - this should potentially be on /flow or /tools/sdk-guidelines.

Also images are not rendering.

**Comment by srinjoyc** [comment]
Intro to Cadence tab (on left menu) should be highlighted when on /cadence but it's not and then when I click on it, it goes to a blank page and errors out.
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/8709330/183722675-12f77bcc-1e01-437f-b5af-9b87dfc85049.png">

**Comment by srinjoyc** [comment]
Cadence (in the menu) is spelled wrong and both links below that title lead to breaking pages.
<img width="302" alt="image" src="https://user-images.githubusercontent.com/8709330/183722932-4f49d917-7427-42d0-8bab-dd0faac73120.png">

**Comment by srinjoyc** [comment]
Setup tab links at the bottom CTAs are not achored to bottom like other tabs:
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/8709330/183736474-228963b6-2824-468f-9555-f337791de1d0.png">

**Comment by joekrill** [comment]
> This is in the wrong place: https://flow-docs-staging.fly.dev/tools/fcl-js/reference/sdk-guidelines - this should potentially be on /flow or /tools/sdk-guidelines.

This sort of fundamentally changes the contract of how the underlying doc repos are supposed to work, no? 

Basically we could do this by adding an additional doc collection as "tools/sdk-guidelines" collection that points to the same repo/source but with a different root directory. But if we do that, we will end up with multiple routes to the same page, because `tools/fcl-js/reference/sdk-guidelines` and any child content will still work and render the same content that  `tools/sdk-guidelines` (and any child pages _there_) do. So we'll really have duplicate pages. We could introduce some sort of "excluded folders" to the manifests maybe, but that's a larger change. Is that something we want to introduce for launch?

The "flow" repo is used across multiple doc collections, but there's no overlap in routes in that case, so duplicate pages isn't really a concern there. 

> 
> Also images are not rendering.

Which images? I'm not able to reproduce this, the images render for me.

**Comment by alxflw** [comment]
- [ ] https://flow-docs-staging.fly.dev/learn/kitty-items/ shows the node operator content:


<img width="1499" alt="Screen Shot 2022-08-09 at 12 18 35 PM" src="https://user-images.githubusercontent.com/97620081/183743229-4b67542d-0b5c-4847-b744-d5ae0aeabf4c.png">

**Comment by srinjoyc** [comment]
@joekrill - You are correct, I mistook sdk-guidelines for another repository but its just a file - it's poorly named and should be called Javascript SDK Examples. So no changed need here, might change file name on FCL end.

> > This is in the wrong place: https://flow-docs-staging.fly.dev/tools/fcl-js/reference/sdk-guidelines - this should potentially be on /flow or /tools/sdk-guidelines.
> 
> This sort of fundamentally changes the contract of how the underlying doc repos are supposed to work, no?
> 
> Basically we could do this by adding an additional doc collection as "tools/sdk-guidelines" collection that points to the same repo/source but with a different root directory. But if we do that, we will end up with multiple routes to the same page, because `tools/fcl-js/reference/sdk-guidelines` and any child content will still work and render the same content that `tools/sdk-guidelines` (and any child pages _there_) do. So we'll really have duplicate pages. We could introduce some sort of "excluded folders" to the manifests maybe, but that's a larger change. Is that something we want to introduce for launch?
> 
> The "flow" repo is used across multiple doc collections, but there's no overlap in routes in that case, so duplicate pages isn't really a concern there.
> 
> > Also images are not rendering.
> 
> Which images? I'm not able to reproduce this, the images render for me.

**Comment by srinjoyc** [comment]
/tools page has link to itself at the 'explore your content' section. 

Also the 'explore your content section' should also be displayed at the bottom (right before footer) on the following pages:
- / (homepage)
- /community
- /learn

The page it's on should not be included in the list.
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/8709330/183743443-cad8393a-d907-461b-8341-9d95bd164dc5.png">

**Comment by alxflw** [comment]
- [ ] https://flow-docs-staging.fly.dev/tools/flow-go-sdk returns a 500 (linked out from the nav as Go SDK

**Comment by alxflw** [comment]
- [ ] All code highlights have one extra new line at the bottom, making it appear as if it it needed:

<img width="866" alt="Screen Shot 2022-08-09 at 12 26 25 PM" src="https://user-images.githubusercontent.com/97620081/183744699-8f3e797e-58ec-42d7-be74-fec532e411ed.png">

https://flow-docs-staging.fly.dev/tools/flow-cli/create-accounts

**Comment by alxflw** [comment]
- [ ] Landing page banner linking out to Cadence tutorials has all broken links:

<img width="1247" alt="Screen Shot 2022-08-09 at 12 29 44 PM" src="https://user-images.githubusercontent.com/97620081/183745140-d3924fd8-4c94-42a9-9cde-2f8b926ce3bf.png">

Links are as such: `https://flow-docs-staging.fly.dev/learn/cadence/tutorial/02-hello-world/` but should be `https://flow-docs-staging.fly.dev/cadence/tutorial/02-hello-world/` (remove `/learn`)

**Comment by srinjoyc** [comment]
Table of contents is showing on FCL API.md - but thought this would be extracted as part of front-matter?:

https://flow-docs-staging.fly.dev/tools/fcl-js/reference/api

**Comment by alxflw** [comment]
- [ ] "View SDKs" button shows up on all sections (APIs, wallets, tools). either should be removed or changed
- [ ] 
<img width="1272" alt="Screen Shot 2022-08-09 at 2 10 32 PM" src="https://user-images.githubusercontent.com/97620081/183762211-9401b4d4-7ba5-45f5-bb9c-33f37cc9b423.png">

**Comment by alxflw** [comment]
- [ ] FLIP section -  "Good places to start" shows _only_ closed issues. Need to filter them out

http://localhost:3000/community

<img width="1147" alt="Screen Shot 2022-08-09 at 2 15 52 PM" src="https://user-images.githubusercontent.com/97620081/183764505-758fc33b-e35c-445e-a8d1-37cb160df6fb.png">

**Comment by alxflw** [comment]
- [ ] Forum list shows GitHub icon - should be removed

<img width="1222" alt="Screen Shot 2022-08-09 at 2 28 28 PM" src="https://user-images.githubusercontent.com/97620081/183764969-b2090f06-3294-4fd7-865f-4b970151d449.png">

http://localhost:3000/community

**Comment by alxflw** [comment]
- [ ] Scroll position behavior is irritating when from one page to another (or back). There's some custom behavior it seems

**Comment by alxflw** [comment]
- [ ] Article timestamp is not anchored to bottom of the card, making it look inconsistent
- [ ] 
<img width="632" alt="Screen Shot 2022-08-09 at 2 34 09 PM" src="https://user-images.githubusercontent.com/97620081/183765866-5cb9a897-41fc-4e56-84a1-ecd4a3833038.png">

http://localhost:3000/learn

**Comment by alxflw** [comment]
- [ ] Article scroller renders the page as text input, should be a label

<img width="213" alt="Screen Shot 2022-08-09 at 2 36 17 PM" src="https://user-images.githubusercontent.com/97620081/183766027-9a4030bc-3fe8-4c6d-aaf6-83d6a6dd4404.png">

**Comment by alxflw** [comment]
- [ ] Featured videos: video title overlay is not visible. Preview icons for other videos on the right aren't showing

<img width="1220" alt="Screen Shot 2022-08-09 at 2 37 47 PM" src="https://user-images.githubusercontent.com/97620081/183766321-79ec9e80-cbf5-4876-acb1-a47eaba2146c.png">

http://localhost:3000/learn

**Comment by alxflw** [comment]
- [ ] (Nice to have, fast follow): Filter behavior is unclear. The toggle icon suggest it is a button to set the filers. The behavior is unclear: is it `OR` or `AND` for multiple tags? it seems and, but it is visually unclear

<img width="1254" alt="Screen Shot 2022-08-09 at 2 39 44 PM" src="https://user-images.githubusercontent.com/97620081/183766728-dabc52f7-6e45-40ae-b7fb-3a96e20c4e5b.png">

http://localhost:3000/learn#all-content

**Comment by srinjoyc** [comment]
> * [ ]  Landing page banner linking out to Cadence tutorials has all broken links:
> 
> <img alt="Screen Shot 2022-08-09 at 12 29 44 PM" width="1247" src="https://user-images.githubusercontent.com/97620081/183745140-d3924fd8-4c94-42a9-9cde-2f8b926ce3bf.png">
> 
> Links are as such: `https://flow-docs-staging.fly.dev/learn/cadence/tutorial/02-hello-world/` but should be `https://flow-docs-staging.fly.dev/cadence/tutorial/02-hello-world/` (remove `/learn`)

This is fixed.

**Comment by srinjoyc** [comment]
> /tools page has link to itself at the 'explore your content' section.
> 
> Also the 'explore your content section' should also be displayed at the bottom (right before footer) on the following pages:
> 
> * / (homepage)
> * /community
> * /learn
> 
> The page it's on should not be included in the list. <img alt="image" width="1316" src="https://user-images.githubusercontent.com/8709330/183743443-cad8393a-d907-461b-8341-9d95bd164dc5.png">

This is fixed.

**Comment by joekrill** [comment]
> * [ ]  Article scroller renders the page as text input, should be a label
> 
> <img alt="Screen Shot 2022-08-09 at 2 36 17 PM" width="213" src="https://user-images.githubusercontent.com/97620081/183766027-9a4030bc-3fe8-4c6d-aaf6-83d6a6dd4404.png">

@alxflw  I believe this was intentional - it's supposed to let someone manually jump to a page by entering it in the input box. Admittedly it's not the best UX (the validation prevents _any_ invalid input at any time, so you have to select the current text completely replace it with a valid page number - otherwise it doesn't appear to do anything). Can you just confirm you want to remove this ability? That's probably much simpler than trying to fix the UX to work better.

**Comment by alxflw** [comment]
> > * [ ]   Article scroller renders the page as text input, should be a label
> > 
> > <img alt="Screen Shot 2022-08-09 at 2 36 17 PM" width="213" src="https://user-images.githubusercontent.com/97620081/183766027-9a4030bc-3fe8-4c6d-aaf6-83d6a6dd4404.png">
> 
> @alxflw I believe this was intentional - it's supposed to let someone manually jump to a page by entering it in the input box. Admittedly it's not the best UX (the validation prevents _any_ invalid input at any time, so you have to select the current text completely replace it with a valid page number - otherwise it doesn't appear to do anything). Can you just confirm you want to remove this ability? That's probably much simpler than trying to fix the UX to work better.

yea, Srinjoy mentioned it as well. let's keep as is in that case
