### ISSUE TITLE
Error with routeModules

### ISSUE THREAD

**Issue by alxflw** [onflow/next-docs-v1#514]
Reported by Sean: 

Occurs when navigating to https://developers.onflow.org/flow/flow-token/available-wallets

![image](https://user-images.githubusercontent.com/97620081/183741700-4944501c-eb55-4aa2-b121-a3b38fc13443.png)

System info:
- MacOS 11.5.2
- Chrome 89

**Comment by 10thfloor** [comment]
Closing because this appears to have been fixed.
