### ISSUE TITLE
Finish Network Page

### ISSUE THREAD

**Issue by srinjoyc** [onflow/next-docs-v1#524]
Few remaining items to get the network page completed.

On /network:
1)  - [x] Update this information on /network (check with protocol team/comms for dates)
<img width="620" alt="image" src="https://user-images.githubusercontent.com/8709330/183917041-c2d107f7-41d9-4052-8395-314866b19a33.png">
2)  - [x] Any "node operator callout" should be the following: "Node Operators" -> Body: "View the current nodes in the network and who is running them. You can use Flow Port to delegate or stake to a node. The picture should be the one of the 'abstract images' used across the site (use best discretion)

When clicking into a details page of a network (/network/:name):
3) - [x] We need to update 
<img width="590" alt="image" src="https://user-images.githubusercontent.com/8709330/183917744-0acfce33-9b19-437b-83c1-84cf463d8194.png">

The RSS feed should point to the RSS subscription feed available at status.onflow.org (in the subscribe for updates). 

Upcoming spork date should be filled in as per protocol team.

4) - [x] For past spork information, they need to be parsed in through this json file: https://github.com/onflow/flow/blob/master/sporks.json

5) - [x] Once 4 is done, the navigation under the network tab should change the link of upcoming and past spork information to those pages. We should also remove or redirect the internal pages in /nodes that contain this same information.

**Comment by aureentuluvacal** [comment]
Just gonna recycle this issue since it still captures all the pieces we need.
