### ISSUE TITLE
FLIP section -  "Good places to start" shows _only_ closed issues. Need to filter them out

### ISSUE THREAD

**Issue by alxflw** [onflow/next-docs-v1#527]
- [ ] FLIP section -  "Good places to start" shows _only_ closed issues. Need to filter them out

http://localhost:3000/community

<img width="1147" alt="Screen Shot 2022-08-09 at 2 15 52 PM" src="https://user-images.githubusercontent.com/97620081/183764505-758fc33b-e35c-445e-a8d1-37cb160df6fb.png">

_Originally posted by @alxflw in https://github.com/onflow/next-docs-v1/issues/510#issuecomment-1209912643_

**Comment by psiemens** [comment]
Related to this, I found it a bit confused that these were under the "FLIPs" header

Maybe the header should be "Contribute to Flow" or something more inclusive?
