### ISSUE TITLE
Doubled Scrollable View on Developer Portal

### ISSUE THREAD

**Issue by a5chanda** [onflow/next-docs-v1#560]
The following bug is back when opening the developer portal on Google Chrome. Both views are scrollable.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/31371847/184250989-08547c53-25bb-4d17-92e7-6f68e1e2458b.png">

**Comment by 10thfloor** [comment]
We tracked this down to a problem with Google Tag Manager. This has been mitigated, but we'll need to create another issue to look into the Tag Manager problem.
