### ISSUE TITLE
Kitty Items video not rendering

### ISSUE THREAD

**Issue by joekrill** [onflow/next-docs-v1#565]
The video [is embedded as an `iframe` in the markdown file](https://raw.githubusercontent.com/onflow/flow/master/docs/content/kitty-items/index.md):

```
<iframe width="100%" height="450" src="https://www.youtube.com/embed/videoseries?list=PL0qVMKzYEBROIztSG9v7-_HiWEDMxz4Ve" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

When we process the markdown we [replace any `<iframe>`  with a `<LargeVideoCard>` component](https://github.com/onflow/next-docs-v1/blob/f738e5f0a0974768d3220a75a026eee718785f01/app/cms/utils/mdx.tsx#L219). The `LargeVideoCard` attempts to extract a video id from the `src`. In this particular case, however, the `src` is a _playlist_ (not a specific video), so the extracted `videoId` that it uses ends up being `null`. But there's no check for that, so it just renders the component using the literal value "null" - so the link doesn't work and the thumbnail image is a generic one.

We need to decide:

1. Do we even want to continue using this `<LargeVideoCard>` at all in these cases? Or should we just pass through the iframe element as-is (which is what was inadvertently happening before #541 "fixed" this)? If the answer is no then we're done here - none of the other questions below are applicable. 
1. If we _do_ want to continue doing the replacement, what do we do when the `src` is not a YouTube embed URL that we can parse (either not a YouTube embed at all, or a YouTube URL we don't recognize)?  Currently one of two things happen: if the URL hostname is "www.youtube.com" we just assume we're going to get a valid `videoId`, which may end up being "null" as described above; otherwise we throw an error which causes the _entire page_ to fail.
1. In this _particular_ case, do we want to figure out how to get the `<LargeVideoCard>` to work with YouTube playlists? These have no `videoId` and it's not clear how easy it will be to get a thumbnail to display. And if the answer is "no", then what do we want to do for this particular scenario (may not be applicable if the answer to question 2, above, is "just pass through as an iframe").

**Comment by srinjoyc** [comment]
Must be a video with a video ID or else you can error out if it is a youtube link in the iframe and render as a card.

If not a youtube link and an iframe, then render nothing but let the page render.
