### ISSUE TITLE
404 for FT standard

### ISSUE THREAD

**Issue by albeethekid** [onflow/next-docs-v1#569]
The link was found on:

https://developers.flow.com/flow/fusd/transactions 

The bad link is:

[FungibleToken](https://developers.flow.com/core-contracts/fungible-token/)

**Comment by 10thfloor** [comment]
@albeethekid The best way to fix this is to load the page, and click the "edit in Github" link in the top-right: 
<img width="1668" alt="Screen Shot 2022-08-16 at 12 28 57 PM" src="https://user-images.githubusercontent.com/901466/184965624-dd17fde6-e7ba-46f7-8e96-ae72d6d9fa8d.png">

Find the dead link in that document and submit a PR. 
Once it is merged, the link will start working in production.
