### ISSUE TITLE
H2 anchor link broken

### ISSUE THREAD

**Issue by alxflw** [onflow/next-docs-v1#588]
For h2 headers, the anchor button is not working

<img width="1083" alt="Screen Shot 2022-08-17 at 10 48 50 AM" src="https://user-images.githubusercontent.com/97620081/185208103-88e93c8b-f7c5-4cdb-b54d-f987b0cb4d79.png">

See https://developers.flow.com/cadence/anti-patterns#

**Comment by 10thfloor** [comment]
https://github.com/onflow/next-docs-v1/issues/581
