### ISSUE TITLE
[due June 20] Generate Menus from markdown content

### ISSUE THREAD

**Issue by 10thfloor** [onflow/next-docs-v1#61]
For docs pages we'll need to generate the required (left and right hand side) menus dynamically as given by the designs.

- [ ] Menus are generated from markdown headings
- [ ] Handles the case where markdown page has no headings
- [ ] Menus are passed to correct layout and page components as props
- [ ] Menus are rendered correctly in the UI

**Comment by schpet** [comment]
@10thfloor @srinjoyc it looks like [the existing docs site]()

has these menus defined in the gatsby config

https://cs.github.com/onflow/flow/blob/55844a8d449e73abdff81bb026f141bcda416dd3/docs/gatsby-config.js?q=%22Cadence+Design+Patterns%22#L340-L349

for this week, do we want to 

a) duplicate that data into this repo
b) try to generate these menus based on the files and directories in the given repos, e.g. cadence? 

a) is faster/easier but what we talked about earlier was more about b) so wanted confirm my approach here.

**Comment by schpet** [comment]
i'll roll with that, thanks @10thfloor – will keep in mind that we want to allow the repos to control this eventually, and i'll base the schema off https://docusaurus.io/docs/sidebar which Alex pointed me towards.

**Comment by schpet** [comment]
this was resolved in PR #161 – please see the details there regarding implementation. basically, for this week we have a way to implement sidebars, and there's a schema there that we could leverage to allow other repos to control their sidebar.
