### ISSUE TITLE
Create Github Action

### ISSUE THREAD

**Issue by srinjoyc** [onflow/next-docs-v1#7]
Use this action to update the redis cache with appropriate content from the originating repo. This should call the refresh endpoint so the server can update the content on the main site.

Input: path to the files that changed in the PR. (diffs in the `docs` folder)

**Requirements:** 

- Action should determine if any `docs` content has changed, and submit which files have changed (repo + paths to files) to Remix backend `/refresh`

- This can be working in dev: `http://localhost:3000/refresh`

- Request should be sent with a security token for authorization. 

- Endpoint should receive:
    - What files changed
    - What files were removed 
    - What files were moved / renamed

Definition of Done:

When a PR is merged into a repository containing this action, a request should be made to the `/refresh` endpoint containing the diff of files that conforms to the interface we decided and a security token for authorization.

**Comment by codingone21** [comment]
Next Steps:
* Merge to cadence master branch
* Finalizing payload (contentPaths, vs Added, Deleted, Modified) with Mackenzie
* Create refresh-calls in FCL repo, and other doc repos
* Replace RequestBin to the actual dev doc web endpoint
