### ISSUE TITLE
[Theme] Scaffold Tailwind theming

### ISSUE THREAD

**Issue by srinjoyc** [onflow/next-docs-v1#8]
# Context
Setup theme files and initial CSS framework based on [Interior Page Starter](https://www.figma.com/file/jxzg0xbPBLbWz2BFsFPPx1/Prototypes?node-id=1343%3A22112) and the [full prototype](https://www.figma.com/proto/jxzg0xbPBLbWz2BFsFPPx1/Prototypes?page-id=1188%3A26801&[…]48%2C0.24&scaling=min-zoom&starting-point-node-id=1188%3A26802](https://www.figma.com/proto/jxzg0xbPBLbWz2BFsFPPx1/Prototypes?page-id=1188%3A26801&node-id=1188%3A26802&viewport=332%2C48%2C0.24&scaling=min-zoom&starting-point-node-id=1188%3A26802)).

# Acceptance Criteria

The theming should do the following:
- [x] Set some initial values for fonts and colors
- [x] Set up dark mode for the interior page
- [x] Set initial breakpoints for mobile

**Comment by srinjoyc** [comment]
Remaining items for theming in new ticket: https://github.com/onflow/next-docs-v1/issues/16

**Comment by 10thfloor** [comment]
@alse Is this finished?

**Comment by alse** [comment]
@10thfloor yes, closing
