### ISSUE TITLE
[due June 20] Update paths to images and other assets

### ISSUE THREAD

**Issue by 10thfloor** [onflow/next-docs-v1#91]
Problem: 
In a github document, living in a repo, you may reference assets (eg images) that are in a folder in the same repo suing a relative path. 

Paths to assets eg `/images/tutorial.jpg` will need to be re-written to the correct fully qualified url: 
- eg `https://github.com/onflow/fcl-js/blob/master/docs/images/tutorial.png`

**Comment by schpet** [comment]
closed by #358
